version: '3.8'

services:
  web:
    build: .
    container_name: django_faq
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
      - REDIS_URL=redis://redis:6379/1

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
